# Generated by Django 5.1.6 on 2025-03-23 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registereduser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("community_leader", "Community Leader"),
                    ("events_leader", "Events Leader"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
